sample/urls.py
from django.urls import path, include
from rest_framework import routers

from sample.views import (
    SampleUserViewSet, SampleGroupViewSet, SampleController, SampleMultiController, SampleInsertExcelController,
    SnippetView, SnippetDetailView, SnippetDetail, SnippetList, StockPriceViewSet
)

router = routers.DefaultRouter()
router.register('users', SampleUserViewSet)
router.register('groups', SampleGroupViewSet)
router.register('stock-price', StockPriceViewSet)

urlpatterns = [
    path('', include(router.urls), name = 'UserSerial'),
    path('api-auth/', include('rest_framework.urls', namespace = 'rest_framework')),

    path('sample', SampleController.as_view(), name = 'Sample'),
    path('sample-multi', SampleMultiController.as_view(), name = 'SampleMulti'),
    path('sample-insert', SampleInsertExcelController.as_view(), name = 'SampleInsertExcel'),

    path('sni', SnippetList.as_view()),
    path('sni/<int:pk>', SnippetDetail.as_view()),

    path('snippets/', SnippetView.as_view()),
    path('snippets/<int:pk>/', SnippetDetailView.as_view()),
]

sample/models.py
import datetime

from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

from sample.querysets import StockPriceQuerySet

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add = True)
    title = models.CharField(max_length = 100, blank = True, default = '')
    code = models.TextField()
    linenos = models.BooleanField(default = False)
    language = models.CharField(choices = LANGUAGE_CHOICES, default = 'python', max_length = 100)
    style = models.CharField(choices = STYLE_CHOICES, default = 'friendly', max_length = 100)

    class Meta:
        ordering = ['created']


class Stocks(models.Model):
    id = models.AutoField(primary_key = True, db_column = 'id')

    stock_code = models.CharField(max_length = 10, unique = True, null = False, db_column = 'stock_code')
    stock_name = models.CharField(max_length = 50, unique = True, null = False, db_column = 'stock_name')

    class Meta:
        managed = True
        db_table = 'stocks'
        ordering = ['id']

    def __str__(self):
        return f'{self.stock_code} / {self.stock_name}'


class StockPrice(models.Model):
    id = models.AutoField(primary_key = True, db_column = 'id')

    open_price = models.IntegerField(blank = False, null = False, db_column = 'open_price')
    high_price = models.IntegerField(blank = False, null = False, db_column = 'high_price')
    low_price = models.IntegerField(blank = False, null = False, db_column = 'low_price')
    close_price = models.IntegerField(blank = False, null = False, db_column = 'close_price')
    date = models.DateField(blank = False, null = False, db_column = 'date')

    stocks_id = models.ForeignKey(Stocks, on_delete = models.DO_NOTHING, db_column = 'stocks_id')

    objects = StockPriceQuerySet.as_manager()

    class Meta:
        managed = True
        db_table = 'stock_price'
        ordering = ['id']

sample/forms.py
from django import forms


class UploadFileForm(forms.Form):
    """
    파일 업로드 Form
    https://docs.djangoproject.com/ko/3.2/topics/http/file-uploads/
    """
    uploadFile = forms.FileField(label = '파일 선택', allow_empty_file = False, )

apps/sample/views.py
import os
from typing import List

import openpyxl
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.base import View
from openpyxl import load_workbook

from amk_demo.settings.base import MEDIA_ROOT
from apps.modules.helpers.upload_file_helper import upload_file_to_server
from apps.modules.mixins.auth_mixins import LoginRequired
from apps.sample.forms import UploadFileForm


class SampleController(LoginRequired, View):
    view_title = '샘플'
    template_name = 'sample/sample_content.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context = {
            'view_title' : self.view_title,
            'upload_form': UploadFileForm()
        })

    def post(self, request, *args, **kwargs):
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            upload_file_to_server(request.FILES.get('uploadFile'))


class SampleMultiController(LoginRequired, View):
    view_title = '샘플'
    template_name = 'sample/sample_multi_content.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context = {
            'view_title' : self.view_title,
            'upload_form': UploadFileForm()
        })


class SampleInsertExcelController(LoginRequired, View):

    def get(self, request, *args, **kwargs):
        filepath = os.path.join(MEDIA_ROOT, 'sample_excel_2.xlsx')
        service = ReadExcelSample(filepath)
        service.operate()

        return HttpResponse('Success')


########################################################################################################################

class DataSampleVO(object):

    def __init__(self, index: str, rack_code: str, product_code: str, register_date: str):
        self._index = index
        self._rack_code = rack_code
        self._product_code = product_code
        self._register_date = register_date

    def validate(self):
        pass

    @property
    def index(self):
        return self._index

    @property
    def rack_code(self):
        return self._rack_code

    @property
    def product_code(self):
        return self._product_code

    @property
    def register_date(self):
        return self._register_date


class ReadExcelSampleAbs(object):
    _workbook: openpyxl.workbook.Workbook

    def __init__(self, filepath: str):
        self._filepath: str = filepath

    def _read_sheet_contents(self):
        raise NotImplementedError('_read_sheet_contents is not implemented')

    def _get_sheet_by_name(self, sheet_name: str):
        return self._workbook[sheet_name]

    def _get_sheet_by_index(self, index: int):
        return self._workbook.worksheets[index]

    def _get_sheet_names(self):
        return self._workbook.sheetnames

    def operate(self):
        self._workbook = load_workbook(filename = self._filepath)
        try:
            datasets = self._read_sheet_contents()
        finally:
            self._workbook.close()

        for d in datasets:
            print(d.index, d.rack_code, d.product_code, d.register_date)


class ReadExcelSample(ReadExcelSampleAbs):
    _skip_sheet_index = [1]
    _min_row = 2

    def _read_sheet_contents(self) -> List[DataSampleVO]:
        result = []
        for sheet_no, sheet_name in enumerate(self._get_sheet_names()):
            rows = self._workbook[sheet_name].iter_rows(min_row = self._min_row)

            for row in rows:
                result.append(self._read_rows(row))

        return result

    def _read_rows(self, row) -> DataSampleVO:
        index, rack_code, product_code, register_date = '', '', '', ''

        for cell in row:
            # print(cell.column_letter, cell.col_idx, cell.value)
            if cell.column_letter == 'A':
                index = cell.value
            if cell.column_letter == 'B':
                rack_code = cell.value
            if cell.column_letter == 'F':
                register_date = cell.value
            if cell.column_letter == 'I':
                product_code = cell.value

        vo = DataSampleVO(index, rack_code, product_code, register_date)
        vo.validate()
        return vo

sample/views.py
import os

from django.core.cache import cache
from django.contrib.auth.models import User, Group
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from rest_framework import viewsets, permissions, mixins, generics
from rest_framework.parsers import JSONParser

from amk_demo.settings.base import MEDIA_ROOT
from file.helpers import upload_file_to_server
from sample.forms import UploadFileForm
from sample.models import Snippet, StockPrice, Stocks
from sample.serializers import SampleUserSerializer, SampleGroupSerializer, SnippetSerializer, StockPriceSerializer
from sample.service.excel.sample_read_excel import ReadExcelSample
from user.mixins import LoginRequired


class SampleController(LoginRequired, View):
    view_title = '샘플'
    template_name = 'sample/sample_content.html'

    def get(self, request, *args, **kwargs):
        # Contrib Message
        from django.contrib import messages
        messages.info(request, "Hello World")

        # Redis Cache
        fromcache = cache.get('stock_price_353')
        if fromcache is None:
            stock_price = StockPrice.objects.filter(stocks_id = Stocks.objects.get(id = '353'))
            cache.set('stock_price_353', stock_price, 60 * 60)
        else:
            stock_price = fromcache

        print(stock_price)

        return render(request, self.template_name, context = {
            'view_title' : self.view_title,
            'upload_form': UploadFileForm()
        })

    def post(self, request, *args, **kwargs):
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            upload_file_to_server(request.FILES.get('uploadFile'))


class SampleMultiController(LoginRequired, View):
    view_title = '샘플'
    template_name = 'sample/sample_multi_content.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context = {
            'view_title' : self.view_title,
            'upload_form': UploadFileForm()
        })


class SampleInsertExcelController(LoginRequired, View):

    def get(self, request, *args, **kwargs):
        filepath = os.path.join(MEDIA_ROOT, 'sample_excel_2.xlsx')
        service = ReadExcelSample(filepath)
        service.operate()

        return HttpResponse('Success')


# ViewSets define the view behavior.
class SampleUserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = SampleUserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class SampleGroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = SampleGroupSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class StockPriceViewSet(viewsets.ModelViewSet):
    queryset = StockPrice.objects.all()
    serializer_class = StockPriceSerializer


# class SnippetView(ListModelMixin, CreateModelMixin, GenericAPIView):
#     queryset = Snippet.objects.all()
#     serializer_class = SnippetSerializer
#
#     def get(self, request, *args, **kwargs):
#         return self.list(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         return self.create(request, *args, **kwargs)


# class SnippetView(ListCreateAPIView):
#     queryset = Snippet.objects.all()
#     serializer_class = SnippetSerializer


class SnippetView(View):

    def get(self, request, *args, **kwargs):
        snippets = Snippet.objects.all()
        serializer = SnippetSerializer(snippets, many = True)
        return JsonResponse(serializer.data, safe = False)

    def post(self, request, *args, **kwargs):
        data = JSONParser().parse(request)
        serializer = SnippetSerializer(data = data)

        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status = 201)

        return JsonResponse(serializer.errors, status = 400)


class SnippetDetailView(View):

    def get(self, request, *args, **kwargs):
        snippet = get_object_or_404(Snippet.objects, id = kwargs['pk'])
        serializer = SnippetSerializer(snippet)
        return JsonResponse(serializer.data)

    def put(self, request, *args, **kwargs):
        snippet = get_object_or_404(Snippet.objects, id = kwargs['pk'])
        data = JSONParser().parse(request)
        serializer = SnippetSerializer(snippet, data = data)

        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)

        return JsonResponse(serializer.errors, status = 400)

    def delete(self, request, *args, **kwargs):
        snippet = get_object_or_404(Snippet.objects, id = kwargs['pk'])
        snippet.delete()
        return HttpResponse(status = 204)


# class SnippetDetail(generics.GenericAPIView,
#                     mixins.ListModelMixin,
#                     mixins.RetrieveModelMixin,
#                     mixins.UpdateModelMixin):
#     queryset = Snippet.objects.all()
#     serializer_class = SnippetSerializer
#
#     def list(self, request, *args, **kwargs):
#         return self.list(request, *args, **kwargs)
#
#     def get(self, request, *args, **kwargs):
#         return self.get(request, *args, **kwargs)
#
#     def update(self, request, *args, **kwargs):
#         return self.update(request, *args, **kwargs)

class SnippetList(generics.ListCreateAPIView):
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer


class SnippetDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer

templates/sample/sample_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ view_title }}</title>
    {% load static %}
    <script src={% static 'comm/jquery_3.4.1.js' %}></script>
    <script src={% static 'comm/jquery.form.min.js' %}></script>

    <script>

        function clear_upload_result()
        {
            $("upload-result").val('');
        }

        function write_upload_result(message)
        {
            $("upload-result").val(message)
        }

        function upload_file()
        {
            {#let file = $("#id_uploadFile", document.uploadFileForm).val();#}
            let uploadFileForm = $("#uploadFileForm");

            uploadFileForm.ajaxForm({
                url: "{% url 'FileUpload' %}",
                enctype: 'multipart/form-data',
                dataType: 'json',
                success: function (result) {
                    console.log(result);
                    write_upload_result(result);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                    write_upload_result(textStatus);
                }
            });
            uploadFileForm.submit();
        }
    </script>
</head>
<body>

<form action="{% url 'FileUpload' %}" method="post" id="uploadFileForm" name="uploadFileForm"
      enctype="multipart/form-data">
    {% csrf_token %}
    {{ upload_form.as_p }}
    <input type="button" class="cm-btn" value="업로드" onclick="upload_file(); return false;">
</form>

<div id="upload-result">
</div>
{% if messages %}
    {{ messages }}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

</body>
</html>

templates/sample/sample_multi_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ view_title }}</title>

    {% load static %}
    <link rel="icon" href="{% static 'comm/favicon.ico' %}">
    <link href="{% static 'comm/bootstrap-5.1.0/css/bootstrap.min.css' %}" rel="stylesheet">

    <script src={% static 'comm/jquery_3.4.1.js' %}></script>
    <script src={% static 'comm/jquery.form.min.js' %}></script>
    <script src={% static 'comm/bootstrap-5.1.0/js/bootstrap.bundle.min.js' %}></script>

    {# https://github.com/danielm/uploader #}
    <link href="{% static 'comm/jquery-uploader/jquery.dm-uploader.min.css' %}" rel="stylesheet">
    <script src={% static 'comm/jquery-uploader/jquery.dm-uploader.min.js' %}></script>
    <script src={% static 'file/uploader.js' %}></script>

    <script>
        $(document).ready(function () {
            make_upload_area("POST", "{% url 'FileUpload' %}", "sample");
        });

    </script>
</head>
<body>
<main class="container pt-2">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            {% csrf_token %}
            <div class="dm-uploader p-5 text-center" id="upload-area">
                <h3 class="mb-5 mt-5 text-muted">Drag &amp; drop Files here</h3>
                <div class="btn btn-primary btn-block mb-5">
                    <span>Open the file Browser</span>
                    <input type="file" title="Click to add Files" multiple="">
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="card h-100">
                <div class="card-header">File List</div>
                <ul class="list-unstyled p-2 d-flex flex-column col" id="files">
                    <li class="text-muted text-center empty">No files uploaded.</li>
                </ul>
            </div>
        </div>
    </div>
</main>

<script type="text/html" id="files-template">
    <li class="media">
        <div class="media-body mb-1">
            <p class="mb-2">
                <strong>%%filename%%</strong> - Status: <span class="text-muted">Waiting</span>
            </p>
            <div class="progress mb-2">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary"
                     role="progressbar"
                     style="width: 0%"
                     aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                </div>
            </div>
            <hr class="mt-1 mb-1"/>
        </div>
    </li>
</script>

<!-- Debug item template -->
<script type="text/html" id="debug-template">
    <li class="list-group-item text-%%color%%"><strong>%%date%%</strong>: %%message%%</li>
</script>

<div id="upload-result">
</div>

</body>
</html>